const { expect } = require('chai')

const sigMaker = require('src/utils/sigMaker')

describe('sigMaker', () => {
  const salt = '12345678'

  const fields = {
    Provider: 'TEST',
    firstname: 'Testy',
    lastname: 'McTestface',
    email: 'testy.mctestface@test.tes',
    Redir: 'https://test.tes/testing'
  }

  // as generated by https://www.md5hashgenerator.com
  // ec78fd5ebe62097ed1b5df017c449bef
  const expected = 'ec78fd5ebe62097ed1b5df017c449bef'

  it('generates the expected sig', () => {
    expect(sigMaker(fields, salt)).to.equal(expected)
  })
})
