const json = `{
  "id": 13668,
  "membershipcode3": "",
  "firstname": "AFCTest",
  "gender": "Male",
  "mail": "afctest@fial.com.au",
  "about": "",
  "externalid": "",
  "postnominal": "",
  "preferredname": "",
  "domembership": "1901-01-01",
  "title": "",
  "qualifications": "",
  "skype": "",
  "idaddressdel": 52323,
  "telfax": "",
  "telddi": "",
  "membershipcode1": "",
  "membershipcode2": "",
  "mailbounces": 0,
  "doacquistion": "2018-05-14",
  "jobtitle": "",
  "initials": "",
  "idaddress": 52323,
  "usertype": "",
  "idaccountpriv": 24686,
  "lastname": "Tester",
  "telbus": "",
  "middlenames": "",
  "telhome": "",
  "dob": "2002-01-01",
  "telmobile": "0000000000",
  "fullname": "AFCTest Tester",
  "mailsecondary": "",
  "mailoptin": true
}`

module.exports = JSON.parse(json)
