const json = `{
  "id": 13669,
  "firstname": "Testy",
  "lastname": "McTestface",
  "fullname": "Testy McTestface",
  "about": "",
  "doacquistion": "2018-05-14",
  "dob": "1996-02-29",
  "domembership": "1901-01-01",
  "externalid": "",
  "gender": "Male",
  "idaccountpriv": 24687,
  "idaddress": 52324,
  "idaddressdel": 0,
  "initials": "",
  "jobtitle": "",
  "mail": "testy.mctestface@test.tes",
  "mailbounces": 0,
  "mailoptin": true,
  "mailsecondary": "",
  "membershipcode1": "",
  "membershipcode2": "",
  "membershipcode3": "",
  "middlenames": "",
  "postnominal": "",
  "preferredname": "",
  "qualifications": "",
  "skype": "",
  "telbus": "",
  "telddi": "",
  "telfax": "",
  "telhome": "",
  "telmobile": "",
  "title": "",
  "usertype": ""
}`

module.exports = JSON.parse(json)
